name: growcoffeeapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_amel_ui_ux.png

  fonts:
    - family: Calistoga
      fonts:
        - asset: assets/fonts/Calistoga-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ThinItalic.ttf
