// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ndDFUR9TnZzhLrjP3bYiL11Miv2FF3w',
    appId: '1:681570825872:web:fdd51932bf3b13707aca15',
    messagingSenderId: '681570825872',
    projectId: 'growcoffeeapp',
    authDomain: 'growcoffeeapp.firebaseapp.com',
    storageBucket: 'growcoffeeapp.firebasestorage.app',
    measurementId: 'G-Z1CTEBHK5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArv5IMZZMiT9jA1cCJw2ZN2hXCOxEvB-g',
    appId: '1:681570825872:android:583c8b5d0a9e81c67aca15',
    messagingSenderId: '681570825872',
    projectId: 'growcoffeeapp',
    storageBucket: 'growcoffeeapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0ndDFUR9TnZzhLrjP3bYiL11Miv2FF3w',
    appId: '1:681570825872:web:894dde2118355e2c7aca15',
    messagingSenderId: '681570825872',
    projectId: 'growcoffeeapp',
    authDomain: 'growcoffeeapp.firebaseapp.com',
    storageBucket: 'growcoffeeapp.firebasestorage.app',
    measurementId: 'G-0YZ5B4D93G',
  );
}
